#Config for ChatItem
#For info visit
#https://www.spigotmc.org/resources/chatitem.19064/

#Version info, DON'T TOUCH
config-version: 4


#The placeholders you want to use for the item. You can add as many as you want.
placeholders:
 - "[i]"
 - "{item}"

#  How will the item be displayed in chat? {name} represents the display name of
# the item, or material name (ex. DIAMOND_SWORD) if it doesn't have a customized
# display name, and {amount} will be replaced by the amount-format configured bellow.
# You can use color codes.
name-format: "&f<&b&l&o{name} {amount}&f>&r"

#  The amount format that will replace the {amount} placeholder in the 'name-format'
# field above. The {times} placeholder represents the number of times the item is
# presented in the itemstack, in other words, the actual item amount in the stack
# the player holds. You can use color codes too.
amount-format: "x{times}"

#  Should we apply the color and formatting defined in the name-format field even if
# the item is already colored/formated (ex. From anvils or other plugins that change
# the display name of an item). I recommend leaving this to true as not applying color
# codes or formatting at all can lead to an unexpected output compared to what you
# actually want, but feel free to experiment with it ;)
color-if-already-colored: true

# Should we add the item amount even if there's only one item in the stack?
force-add-amount: true

# Should we cancel the user message if the item in his (main) hand is air or null? (No item in hand, that is)
deny-if-no-item: true

#  If so, what message should the user get upon attempting to send such a message? Set to "" to disable.
deny-message: "&c&lYou have no item in hand!"

#  The message you will get after reloading the plugin using /cireload.
reload-success: "&b&lSuccessful reload!"



#  Translations
Translations:
  STONE:
    1: "Granite"
#  The above field is a little more complicated, but I'll explain you:
# You may have noticed that (until now) if using the placeholder
# with an item such as Granite in hand, (unless it's display name
# is changed) the item will display in chat as (for granite) Stone.
# That happens because the plugin is set to use the material
# name of the item if no custom displayname is found on it.
# The material name for both stone and granite is STONE, the
# only difference being the data value, stone being STONE:0
# and granite being STONE:1. In order to make things more user
# friendly, I implemented this translation feature. Here's how it works:
# If you want to display STONE:1 as GRANITE in chat, you should
# add the following line under translations:
# STONE:
#   1: "Granite"
# STONE represents the material name of the item, while it's sub-section
# '1' represents the data value of the item. The thing that comes next is
# what should actually be displayed in chat.
# You can find a list of item materials and data values
# here: http://www.minecraftinfo.com/idlist.html